#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "Transpiling ldpp.ls..."
npx lsc -cp --no-header src/ldpp.ls > dist/ldpp.raw.js
echo "Transpiling ldpe.ls..."
npx lsc -cp --no-header  src/ldpe.ls > dist/ldpe.js
echo "Transpiling ldp.ls..."
npx lsc -cp --no-header  src/ldp.ls > dist/ldp.js
echo "Transpiling ldpp.styl..."
npx stylus -p src/ldpp.styl > dist/ldpp.css
echo "Uglifying ldpp.raw.js..."
npx uglifyjs dist/ldpp.raw.js > dist/ldpp.raw.min.js
echo "Uglifying ldpe.js..."
npx uglifyjs dist/ldpe.js > dist/ldpe.min.js
echo "Uglifying ldp.js..."
npx uglifyjs dist/ldp.js > dist/ldp.min.js
echo "Merge ldpe and ldpp..."
cat dist/ldpp.raw.js dist/ldpe.js dist/ldp.js > dist/ldpp.js
cat dist/ldpp.raw.min.js dist/ldpe.min.js dist/ldp.min.js > dist/ldpp.min.js
echo "Uglifying ldpp.css..."
uglifycss dist/ldpp.css > dist/ldpp.min.css
echo "Copy palettes presets to dist/ ..."
cp tool/js/*.js dist/
echo "Copy pug mixin to dist/ ..."
cp src/ldpp.pug dist/
echo "Deploy to web ... "
rm -rf web/static/assets/lib/ldpalettepicker/dev
mkdir -p web/static/assets/lib/ldpalettepicker/dev
cp -R dist/* web/static/assets/lib/ldpalettepicker/dev/
echo "Done."

